# Generated by Django 4.2.1 on 2023-05-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eproduct',
            fields=[
                ('eproductID', models.AutoField(primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('productType', models.CharField(max_length=100)),
                ('productPrice', models.CharField(max_length=100)),
                ('productCompany', models.CharField(max_length=100)),
            ],
        ),
    ]
